import type { Metadata } from 'next';

import '../globals.css';
import MapContainer from '@/components/MapContainer';
import React from 'react';
import StepperWrapper from '@/components/StepWrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="mt-[3%] flex justify-center">
        <StepperWrapper />
      </div>
      <div className="mt-[5%] flex justify-center gap-[10rem] px-[3%]">
        <div className="">
          {children} {/* your pages go here */}
        </div>
        <MapContainer />
      </div>
    </>
  );
}
